package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	"iam_services_main_v1/gql/generated"
	"iam_services_main_v1/gql/models"
)

// Tenant is the resolver for the tenant field.
func (r *clientOrganizationUnitResolver) Tenant(ctx context.Context, obj *models.ClientOrganizationUnit) (*models.Tenant, error) {
	panic(fmt.Errorf("not implemented: Tenant - tenant"))
}

// ParentOrg is the resolver for the parentOrg field.
func (r *clientOrganizationUnitResolver) ParentOrg(ctx context.Context, obj *models.ClientOrganizationUnit) (models.Organization, error) {
	panic(fmt.Errorf("not implemented: ParentOrg - parentOrg"))
}

// ClientOrganizationUnit returns generated.ClientOrganizationUnitResolver implementation.
func (r *Resolver) ClientOrganizationUnit() generated.ClientOrganizationUnitResolver {
	return &clientOrganizationUnitResolver{r}
}

type clientOrganizationUnitResolver struct{ *Resolver }
