package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	generated1 "iam_services_main_v1/gql/generated"
	models1 "iam_services_main_v1/gql/models"

	"github.com/google/uuid"
)

// CreateTenant is the resolver for the createTenant field.
func (r *mutationResolver) CreateTenant(ctx context.Context, input models1.CreateTenantInput) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: CreateTenant - createTenant"))
}

// UpdateTenant is the resolver for the updateTenant field.
func (r *mutationResolver) UpdateTenant(ctx context.Context, input models1.UpdateTenantInput) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: UpdateTenant - updateTenant"))
}

// DeleteTenant is the resolver for the deleteTenant field.
func (r *mutationResolver) DeleteTenant(ctx context.Context, id uuid.UUID) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: DeleteTenant - deleteTenant"))
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input models1.CreateRoleInput) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: CreateRole - createRole"))
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, input models1.UpdateRoleInput) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: UpdateRole - updateRole"))
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id uuid.UUID) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: DeleteRole - deleteRole"))
}

// GetTenant is the resolver for the getTenant field.
func (r *queryResolver) GetTenant(ctx context.Context, id uuid.UUID) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: GetTenant - getTenant"))
}

// AllTenants is the resolver for the allTenants field.
func (r *queryResolver) AllTenants(ctx context.Context) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: AllTenants - allTenants"))
}

// GetRole is the resolver for the getRole field.
func (r *queryResolver) GetRole(ctx context.Context, id uuid.UUID) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: GetRole - getRole"))
}

// AllRoles is the resolver for the allRoles field.
func (r *queryResolver) AllRoles(ctx context.Context) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: AllRoles - allRoles"))
}

// Mutation returns generated1.MutationResolver implementation.
func (r *Resolver) Mutation() generated1.MutationResolver { return &mutationResolver{r} }

// Query returns generated1.QueryResolver implementation.
func (r *Resolver) Query() generated1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreatePermission(ctx context.Context, input models1.CreatePermission) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: CreatePermission - createPermission"))
}
func (r *mutationResolver) UpdatePermission(ctx context.Context, input models1.UpdatePermission) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: UpdatePermission - updatePermission"))
}
func (r *mutationResolver) DeletePermission(ctx context.Context, id uuid.UUID) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: DeletePermission - deletePermission"))
}
func (r *queryResolver) GetAllPermissions(ctx context.Context) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: GetAllPermissions - getAllPermissions"))
}
func (r *queryResolver) GetPermission(ctx context.Context, id uuid.UUID) (models1.OperationResult, error) {
	panic(fmt.Errorf("not implemented: GetPermission - getPermission"))
}
*/
