package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"
	"fmt"
	"iam_services_main_v1/gql/generated"
	"iam_services_main_v1/gql/models"
)

// ContactInfo is the resolver for the contactInfo field.
func (r *tenantResolver) ContactInfo(ctx context.Context, obj *models.Tenant) (*models.ContactInfo, error) {
	panic(fmt.Errorf("not implemented: ContactInfo - contactInfo"))
}

// Tenant returns generated.TenantResolver implementation.
func (r *Resolver) Tenant() generated.TenantResolver { return &tenantResolver{r} }

type tenantResolver struct{ *Resolver }
