// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type RoleAssignment struct {
	Role   string `json:"role"`
	Tenant string `json:"tenant"`
}

type RoleAssignmentInput struct {
	Role   string `json:"role"`
	Tenant string `json:"tenant"`
}

type Subscription struct {
}

type SubscriptionInput struct {
	Tier    string `json:"tier"`
	Expired bool   `json:"expired"`
}

type Tenant struct {
	ID             string            `json:"id"`
	OrganizationID string            `json:"organizationId"`
	ProjectID      string            `json:"projectId"`
	EnvironmentID  string            `json:"environmentId"`
	CreatedAt      string            `json:"createdAt"`
	UpdatedAt      string            `json:"updatedAt"`
	LastActionAt   string            `json:"lastActionAt"`
	Key            string            `json:"key"`
	Name           string            `json:"name"`
	Attributes     *TenantAttributes `json:"attributes"`
}

type TenantAttributes struct {
	AllowedLocations []*string `json:"allowedLocations"`
}

type TenantAttributesInput struct {
	AllowedLocations []*string `json:"allowedLocations"`
}

type TenantInput struct {
	OrganizationID string                 `json:"organizationId"`
	ProjectID      string                 `json:"projectId"`
	EnvironmentID  string                 `json:"environmentId"`
	Key            string                 `json:"key"`
	Name           string                 `json:"name"`
	Attributes     *TenantAttributesInput `json:"attributes"`
}

type User struct {
	Key             string            `json:"key"`
	Email           string            `json:"email"`
	FirstName       string            `json:"firstName"`
	LastName        string            `json:"lastName"`
	Attributes      *UserAttributes   `json:"attributes"`
	RoleAssignments []*RoleAssignment `json:"roleAssignments"`
}

type UserAttributes struct {
	Department   *string       `json:"department,omitempty"`
	Age          *int          `json:"age,omitempty"`
	Subscription *Subscription `json:"subscription,omitempty"`
}

type UserAttributesInput struct {
	Department   *string            `json:"department,omitempty"`
	Age          *int               `json:"age,omitempty"`
	Subscription *SubscriptionInput `json:"subscription,omitempty"`
}

type UserInput struct {
	Email           string                 `json:"email"`
	FirstName       string                 `json:"firstName"`
	LastName        string                 `json:"lastName"`
	Attributes      *UserAttributesInput   `json:"attributes"`
	RoleAssignments []*RoleAssignmentInput `json:"roleAssignments"`
}
