package controller

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"
)

// Tier is the resolver for the tier field.
func (r *subscriptionResolver) Tier(ctx context.Context) (<-chan string, error) {
	panic(fmt.Errorf("not implemented: Tier - tier"))
}

// Expired is the resolver for the expired field.
func (r *subscriptionResolver) Expired(ctx context.Context) (<-chan bool, error) {
	panic(fmt.Errorf("not implemented: Expired - expired"))
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
